// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpgmrhncMX6GO5Gj13bKV6nAQwKK1EMo',
    appId: '1:896208413196:web:44687208b249445021c429',
    messagingSenderId: '896208413196',
    projectId: 'uems-de31f',
    authDomain: 'uems-de31f.firebaseapp.com',
    storageBucket: 'uems-de31f.firebasestorage.app',
    measurementId: 'G-YX7X5XX9ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmfSAopVnQpwqS6yrBfNWTzczJPsWPdAM',
    appId: '1:896208413196:android:25b999b06bb4b3c521c429',
    messagingSenderId: '896208413196',
    projectId: 'uems-de31f',
    storageBucket: 'uems-de31f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQyZZh5Hjtmm2lIW-34RmZ8PIpaucrwkA',
    appId: '1:896208413196:ios:afb262d1e376c7a621c429',
    messagingSenderId: '896208413196',
    projectId: 'uems-de31f',
    storageBucket: 'uems-de31f.firebasestorage.app',
    iosBundleId: 'com.example.uems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQyZZh5Hjtmm2lIW-34RmZ8PIpaucrwkA',
    appId: '1:896208413196:ios:afb262d1e376c7a621c429',
    messagingSenderId: '896208413196',
    projectId: 'uems-de31f',
    storageBucket: 'uems-de31f.firebasestorage.app',
    iosBundleId: 'com.example.uems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpgmrhncMX6GO5Gj13bKV6nAQwKK1EMo',
    appId: '1:896208413196:web:2e5d0f1df505906421c429',
    messagingSenderId: '896208413196',
    projectId: 'uems-de31f',
    authDomain: 'uems-de31f.firebaseapp.com',
    storageBucket: 'uems-de31f.firebasestorage.app',
    measurementId: 'G-TR1J0ZF6QT',
  );
}
